export const pokemons = [
    { name: 'Bulbasaur', description: 'Bulbasaur può essere visto mentre dorme alla luce del sole. C\'è un seme sulla sua schiena. Assorbendo i raggi del sole, il seme cresce progressivamente.' },
    { name: 'Ivysaur', description: 'Quando il bulbo sulla sua schiena cresce, sembra perdere la capacità di stare in piedi sulle zampe posteriori. La dimensione del bulbo suggerisce che stia assorbendo nutrienti.' },
    { name: 'Venusaur', description: 'La pianta fiorisce quando assorbe l\'energia solare. Rimane in movimento per cercare la luce del sole.' },
    { name: 'Charmander', description: 'La vita di Charmander gira attorno alla sua fiamma sulla coda. Se la fiamma si spegne, si dice che Charmander muoia.' },
    { name: 'Charmeleon', description: 'L\'aggressività di Charmeleon fa flare la sua fiamma. Maggiore è la fiamma, più aggressivamente attacca.' },
    { name: 'Charizard', description: 'Charizard vola bruciando il paesaggio con le sue fiamme. Il suo respiro infuocato può sciogliere qualsiasi cosa.' },
    { name: 'Squirtle', description: 'Il guscio di Squirtle non è solo per protezione. Il suo guscio assorbe l\'acqua e, con abbastanza acqua, può lanciare un potente attacco Idropompa.' },
    { name: 'Wartortle', description: 'La lunga coda di Wartortle è un segno della sua maturità. La coda è un indicatore della sua età e forza.' },
    { name: 'Blastoise', description: 'I cannoni d\'acqua di Blastoise possono sparare potenti getti d\'acqua. I suoi potenti attacchi possono rompere rocce e barriere.' },
    { name: 'Caterpie', description: 'Il corpo di Caterpie è morbido e flessibile e può allungarsi facilmente. Può produrre seta per creare un bozzolo.' },
    { name: 'Metapod', description: 'Metapod è un bozzolo che protegge l\'insetto all\'interno. Il guscio è duro e lo proteggerà dai predatori.' },
    { name: 'Butterfree', description: 'Le ali di Butterfree hanno una polvere tossica. Può diffondere la polvere per stordire i nemici e fuggire.' },
    { name: 'Weedle', description: 'Il veleno di Weedle è pericoloso. Inietta il suo veleno quando si sente minacciato per difendersi.' },
    { name: 'Kakuna', description: 'Kakuna è un bozzolo che protegge il bug all\'interno. Sta aspettando di trasformarsi in un potente Pokémon.' },
    { name: 'Beedrill', description: 'Beedrill ha tre pungiglioni velenosi sulle ali e la coda. È estremamente aggressivo e attacca senza pietà.' },
    { name: 'Pidgey', description: 'Pidgey ha un grande senso di orientamento e può trovare la sua strada anche nei luoghi più oscuri.' },
    { name: 'Pidgeotto', description: 'Pidgeotto ha una grande forza e può volare a grande velocità. Utilizza il suo becco per attaccare i nemici.' },
    { name: 'Pidgeot', description: 'Pidgeot è uno dei Pokémon più veloci in volo. Le sue ali possono creare potenti venti.' },
    { name: 'Rattata', description: 'Rattata è un Pokémon molto vivace e rapido. Può mordere con forza usando i suoi denti aguzzi.' },
    { name: 'Raticate', description: 'Raticate è molto aggressivo e può attaccare con i suoi forti denti. È veloce e può mordere con grande forza.' },
    { name: 'Spearow', description: 'Spearow è un Pokémon aggressivo e può attaccare con il suo becco affilato. È molto veloce nel volo.' },
    { name: 'Fearow', description: 'Fearow ha ali larghe che gli permettono di volare a grande velocità. Può colpire con il suo becco affilato.' },
    { name: 'Ekans', description: 'Ekans è un Pokémon serpente che può avvolgere le sue prede con il suo corpo per immobilizzarle.' },
    { name: 'Arbok', description: 'Arbok ha una pelle a strisce che può cambiare colore. Il suo veleno è estremamente pericoloso.' },
    { name: 'Pikachu', description: 'Pikachu è noto per le sue capacità elettriche. Può generare elettricità e sprigionarla attraverso le sue guance.' },
    { name: 'Raichu', description: 'Raichu può generare e scaricare energia elettrica con grande potenza. È molto veloce e agile.' },
    { name: 'Sandshrew', description: 'Sandshrew è un Pokémon di tipo terra con una pelle spessa e dura. Può scavare rapidamente nel terreno.' },
    { name: 'Sandslash', description: 'Sandslash ha artigli affilati che può usare per scavare e difendersi. È molto agile e resistente.' },
    { name: 'Nidoran♀', description: 'Nidoran♀ ha punte velenose sulle sue zampe e sul corpo. Può emettere un veleno potente quando minacciata.' },
    { name: 'Nidorina', description: 'Nidorina è più grande di Nidoran♀ e ha punte velenose più sviluppate. Può usare il suo veleno per difendersi.' },
    { name: 'Nidoqueen', description: 'Nidoqueen è molto forte e resistente. Può utilizzare il suo veleno e le sue capacità di difesa per proteggersi.' },
    { name: 'Nidoran♂', description: 'Nidoran♂ ha spine velenose sulle sue spalle. Può attaccare con il suo veleno quando si sente minacciato.' },
    { name: 'Nidorino', description: 'Nidorino è più grande e più potente di Nidoran♂. Ha punte velenose più lunghe e può attaccare con maggiore forza.' },
    { name: 'Nidoking', description: 'Nidoking è un Pokémon molto potente. Ha punte velenose e può scatenare attacchi devastanti.' },
    { name: 'Clefairy', description: 'Clefairy è noto per la sua capacità di volare attraverso la luna. Può emettere una luce magica quando è felice.' },
    { name: 'Clefable', description: 'Clefable ha una grande abilità magica e può utilizzare diverse tecniche di difesa e attacco.' },
    { name: 'Vulpix', description: 'Vulpix ha sei code che possono sprigionare fiamme. Può attaccare con fuoco e calore.' },
    { name: 'Ninetales', description: 'Ninetales ha nove code che emettono fiamme. Può scatenare potenti attacchi di fuoco.' },
    { name: 'Jigglypuff', description: 'Jigglypuff può cantare una melodia ipnotica che fa addormentare chiunque la ascolti.' },
    { name: 'Wigglytuff', description: 'Wigglytuff ha una voce ancora più potente di Jigglypuff. Può usare la sua canzone per far addormentare gli avversari.' },
    { name: 'Zubat', description: 'Zubat è un Pokémon che usa l\'ecolocalizzazione per orientarsi. È attivo soprattutto nei luoghi bui.' },
    { name: 'Golbat', description: 'Golbat ha le ali grandi che può usare per volare rapidamente. È noto per i suoi attacchi succhiatori.' },
    { name: 'Diglett', description: 'Diglett vive sottoterra e può emergere rapidamente. È difficile da vedere e catturare.' },
    { name: 'Dugtrio', description: 'Dugtrio è composto da tre Diglett che lavorano insieme. È molto veloce e può causare terremoti.' },
    { name: 'Meowth', description: 'Meowth è un Pokémon molto furbo e ama collezionare monete. Può camminare sulle due zampe posteriori.' },
    { name: 'Persian', description: 'Persian è un Pokémon elegante e veloce. Può attaccare con le sue artigli affilati.' },
    { name: 'Psyduck', description: 'Psyduck ha frequenti mal di testa che lo fanno usare i suoi poteri psichici. È noto per il suo comportamento confuso.' },
    { name: 'Golduck', description: 'Golduck è molto agile in acqua e può usare poteri psichici per attaccare e difendersi.' },
    { name: 'Mankey', description: 'Mankey è noto per la sua aggressività. Può attaccare con le sue zampe e le sue mani forti.' },
    { name: 'Primeape', description: 'Primeape è estremamente arrabbiato e può attaccare senza pietà. È molto forte e veloce.' },
    { name: 'Growlithe', description: 'Growlithe è un cucciolo di Pokémon che può emettere fiamme. È molto leale e affettuoso.' },
    { name: 'Arcanine', description: 'Arcanine è un Pokémon maestoso e veloce. Ha fiamme ardenti che emettono dal suo corpo.' },
    { name: 'Poliwag', description: 'Poliwag è un Pokémon anfibio che può nuotare bene. Ha una pelle che cambia colore con l\'età.' },
    { name: 'Poliwhirl', description: 'Poliwhirl ha una grande forza e può usare i suoi pugni per attaccare. È molto agile sia in acqua che a terra.' },
    { name: 'Poliwrath', description: 'Poliwrath è un Pokémon potente e agile. Può usare i suoi pugni e le sue abilità di nuoto per combattere.' },
    { name: 'Abra', description: 'Abra è noto per la sua capacità di teletrasportarsi. Passa gran parte del tempo dormendo.' },
    { name: 'Kadabra', description: 'Kadabra ha potenti abilità psichiche e può usare il suo bastone per canalizzare il suo potere.' },
    { name: 'Alakazam', description: 'Alakazam ha una memoria incredibile e può usare poteri psichici molto avanzati. È molto intelligente.' },
    { name: 'Machop', description: 'Machop è un Pokémon muscoloso e forte. Può sollevare pesi e combattere con grande forza.' },
    { name: 'Machoke', description: 'Machoke è ancora più forte di Machop. Può sollevare pesi enormi e combattere con grande potenza.' },
    { name: 'Machamp', description: 'Machamp ha quattro braccia che può usare per attaccare. È uno dei Pokémon più forti in combattimento.' },
    { name: 'Bellsprout', description: 'Bellsprout è un Pokémon che può crescere in altezza. Usa le sue foglie per assorbire la luce solare.' },
    { name: 'Weepinbell', description: 'Weepinbell può lanciare il suo corpo come una clessidra per catturare le sue prede. Usa le sue foglie per assorbire energia.' },
    { name: 'Victreebel', description: 'Victreebel è noto per la sua bocca a forma di campana. Può inghiottire completamente le sue prede.' },
    { name: 'Tentacool', description: 'Tentacool vive nell\'acqua e può spruzzare un veleno tossico dai suoi tentacoli.' },
    { name: 'Tentacruel', description: 'Tentacruel è un Pokémon acquatico con molti tentacoli che può spruzzare veleno e attaccare i nemici.' },
    { name: 'Geodude', description: 'Geodude è un Pokémon di roccia e terra con un corpo roccioso e robusto. Può usare le sue braccia per attaccare.' },
    { name: 'Graveler', description: 'Graveler è molto veloce e può rotolare come una palla di roccia. È un Pokémon potente e difficile da fermare.' },
    { name: 'Golem', description: 'Golem è un Pokémon di roccia e terra con una pelle dura. Può generare forti esplosioni e terremoti.' },
    { name: 'Ponyta', description: 'Ponyta è un Pokémon cavallo con una fiamma sulla criniera. Può correre a velocità elevata.' },
    { name: 'Rapidash', description: 'Rapidash è un Pokémon cavallo che può correre a velocità supersonica. Le sue fiamme possono bruciare tutto.' },
    { name: 'Slowpoke', description: 'Slowpoke è noto per la sua lentezza. Può muovere lentamente le sue zampe e la sua lingua.' },
    { name: 'Slowbro', description: 'Slowbro è un Pokémon tranquillo che ha un Shellder attaccato alla sua coda. Il Shellder aumenta la sua forza.' },
    { name: 'Magnemite', description: 'Magnemite è un Pokémon di tipo elettromagnetico con una forza magnetica che può attirare metalli.' },
    { name: 'Magneton', description: 'Magneton è composto da tre Magnemite uniti. Può generare un forte campo magnetico.' },
    { name: 'Farfetch\'d', description: 'Farfetch\'d è noto per portare sempre un porro. Usa il porro come arma per difendersi.' },
    { name: 'Doduo', description: 'Doduo è un Pokémon con due teste e quattro zampe. È molto veloce e può correre a grandi velocità.' },
    { name: 'Dodrio', description: 'Dodrio ha tre teste e può attaccare con grande forza. È molto rapido e agile.' },
    { name: 'Seel', description: 'Seel è un Pokémon acquatico che vive in acque fredde. Può congelare l\'acqua con i suoi attacchi.' },
    { name: 'Dewgong', description: 'Dewgong è un Pokémon di ghiaccio e acqua con un corpo elegante. Può congelare l\'acqua e nuotare rapidamente.' },
    { name: 'Grimer', description: 'Grimer è un Pokémon di tipo velenoso che vive in ambienti inquinati. Può creare fumi tossici.' },
    { name: 'Muk', description: 'Muk è composto da una massa di veleno. È molto pericoloso e può emettere gas tossici.' },
    { name: 'Shellder', description: 'Shellder è un Pokémon di tipo acqua con una conchiglia dura. Può chiudere la conchiglia per proteggersi.' },
    { name: 'Cloyster', description: 'Cloyster ha una conchiglia molto dura e può emettere potenti attacchi d\'acqua. È difficile da rompere.' },
    { name: 'Gastly', description: 'Gastly è un Pokémon di tipo spettro e veleno che può avvolgere i suoi nemici con una nebbia tossica.' },
    { name: 'Haunter', description: 'Haunter è un Pokémon spettrale che può attraversare gli oggetti e terrorizzare i suoi nemici.' },
    { name: 'Gengar', description: 'Gengar è un Pokémon spettrale molto astuto. Può manipolare le ombre e usare le sue abilità per spaventare.' },
    { name: 'Onix', description: 'Onix è un Pokémon di roccia e terra con un corpo serpentino composto da rocce. Può scavare nel terreno.' },
    { name: 'Steelix', description: 'Steelix è una versione evoluta di Onix con un corpo di metallo. È molto resistente e può generare forti terremoti.' },
    { name: 'Drowzee', description: 'Drowzee può indurre il sonno nei suoi avversari usando i suoi poteri psichici. Ama mangiare sogni.' },
    { name: 'Hypno', description: 'Hypno usa il suo pendolo per indurre il sonno e manipolare i sogni. È molto abile con i poteri psichici.' },
    { name: 'Krabby', description: 'Krabby è un Pokémon granchio con artigli potenti. Può attaccare con grande forza usando i suoi artigli.' },
    { name: 'Kingler', description: 'Kingler è un Pokémon granchio evoluto con artigli ancora più potenti. Può usare i suoi artigli per difendersi e attaccare.' },
    { name: 'Voltorb', description: 'Voltorb è un Pokémon che assomiglia a una sfera elettrica. Può esplodere se provocato.' },
    { name: 'Electrode', description: 'Electrode è la versione evoluta di Voltorb e può esplodere con maggiore potenza. È molto veloce.' },
    { name: 'Exeggcute', description: 'Exeggcute è un gruppo di sei uova che possono usare attacchi psichici. Sono noti per la loro capacità di evolversi in Exeggutor.' },
    { name: 'Exeggutor', description: 'Exeggutor è un Pokémon composto da tre teste e può usare potenti attacchi psichici. È molto resistente.' },
    { name: 'Cubone', description: 'Cubone è un Pokémon che indossa un teschio come elmo. Usa il suo osso come arma per combattere.' },
    { name: 'Marowak', description: 'Marowak è un Pokémon evoluto che usa un grande osso come arma. È noto per la sua forza e abilità nel combattere.' },
    { name: 'Hitmonlee', description: 'Hitmonlee è un Pokémon esperto nelle arti marziali e può lanciare calci potenti. È molto agile.' },
    { name: 'Hitmonchan', description: 'Hitmonchan è un esperto di arti marziali e può colpire con pugni veloci e potenti. È molto veloce.' },
    { name: 'Lickitung', description: 'Lickitung ha una lingua lunga e appiccicosa che può usare per afferrare e mangiare il cibo.' },
    { name: 'Koffing', description: 'Koffing è un Pokémon di tipo velenoso che emette gas tossici. Può creare fumi tossici per difendersi.' },
    { name: 'Weezing', description: 'Weezing è composto da due Koffing uniti. Può emettere fumi tossici in grandi quantità.' },
    { name: 'Rhyhorn', description: 'Rhyhorn è un Pokémon robusto con una pelle dura. Può caricare con grande forza e spingere via i suoi nemici.' },
    { name: 'Rhydon', description: 'Rhydon è una versione evoluta di Rhyhorn e ha una pelle ancora più dura. È molto potente e resistente.' },
    { name: 'Chansey', description: 'Chansey è un Pokémon che ha un grande cuore e può curare le sue ferite con il suo uovo.' },
    { name: 'Blissey', description: 'Blissey è un Pokémon molto gentile e affettuoso. Può curare e far sentire meglio chiunque sia vicino a lei.' },
    { name: 'Tangela', description: 'Tangela è un Pokémon coperto di viti e può avvolgere i suoi nemici con le sue radici.' },
    { name: 'Tangrowth', description: 'Tangrowth è la versione evoluta di Tangela e ha una maggiore quantità di viti e radici. Può usare queste radici per combattere.' },
    { name: 'Kangaskhan', description: 'Kangaskhan è un Pokémon che porta sempre il suo cucciolo nella sacca sulla pancia. È molto protettivo.' },
    { name: 'Horsea', description: 'Horsea è un Pokémon acquatico con un corpo a forma di cavalluccio marino. Può spruzzare acqua con precisione.' },
    { name: 'Seadra', description: 'Seadra è una versione evoluta di Horsea e può generare potenti getti d\'acqua. È molto veloce in acqua.' },
    { name: 'Goldeen', description: 'Goldeen è un Pokémon pesce con una pinna elegante. Può attaccare con la sua pinna tagliente.' },
    { name: 'Seaking', description: 'Seaking è una versione evoluta di Goldeen e può utilizzare potenti attacchi d\'acqua. È molto forte.' },
    { name: 'Staryu', description: 'Staryu è un Pokémon acquatico che ha una gemma al centro del corpo. Può rigenerare i suoi arti.' },
    { name: 'Starmie', description: 'Starmie è la versione evoluta di Staryu e ha una gemma più grande. È molto veloce e può usare attacchi d\'acqua.' },
    { name: 'Mr. Mime', description: 'Mr. Mime è un Pokémon psichico che può creare barriere invisibili per proteggersi e difendersi.' },
    { name: 'Scyther', description: 'Scyther è un Pokémon con grandi ali e arti a forma di falce. È molto veloce e abile in combattimento.' },
    { name: 'Jynx', description: 'Jynx ha un corpo di ghiaccio e può emettere potenti attacchi congelanti. È molto elegante e agile.' },
    { name: 'Electabuzz', description: 'Electabuzz è un Pokémon elettrico con poteri elettrici. Può scaricare elettricità con grande forza.' },
    { name: 'Magmar', description: 'Magmar è un Pokémon di fuoco con un corpo che emette calore. Può generare fiamme intense.' },
    { name: 'Pinsir', description: 'Pinsir ha forti mandibole che può usare per schiacciare e afferrare i suoi nemici.' },
    { name: 'Tauros', description: 'Tauros è un Pokémon toro che può caricare con grande forza. È molto aggressivo in battaglia.' },
    { name: 'Magikarp', description: 'Magikarp è noto per la sua debolezza. Tuttavia, può evolversi in un Pokémon molto potente.' },
    { name: 'Gyarados', description: 'Gyarados è una versione evoluta di Magikarp e ha una grande forza e abilità. Può causare tempeste e distruzione.' },
    { name: 'Lapras', description: 'Lapras è un Pokémon acquatico che può trasportare persone sulle sue spalle. È molto gentile e intelligente.' },
    { name: 'Ditto', description: 'Ditto può trasformarsi in qualsiasi altro Pokémon. È noto per la sua capacità di imitare.' },
    { name: 'Eevee', description: 'Eevee è un Pokémon che può evolversi in molte forme diverse a seconda delle condizioni e degli elementi.' },
    { name: 'Vaporeon', description: 'Vaporeon è una delle evoluzioni di Eevee e può manipolare l\'acqua. È molto elegante e agile.' },
    { name: 'Jolteon', description: 'Jolteon è un\'evoluzione di Eevee che ha poteri elettrici. È molto veloce e può scaricare energia elettrica.' },
    { name: 'Flareon', description: 'Flareon è una delle evoluzioni di Eevee e ha poteri di fuoco. Può emettere fiamme molto calde.' },
    { name: 'Porygon', description: 'Porygon è un Pokémon di tipo normale che può cambiare il suo corpo. Può adattarsi a diversi ambienti.' },
    { name: 'Porygon2', description: 'Porygon2 è la versione evoluta di Porygon e può accedere a nuovi poteri e abilità.' },
    { name: 'Omanyte', description: 'Omanyte è un Pokémon fossile con un guscio a spirale. Può emettere potenti getti d\'acqua.' },
    { name: 'Omastar', description: 'Omastar è la versione evoluta di Omanyte e ha un guscio più grande. Può attaccare con i suoi tentacoli.' },
    { name: 'Kabuto', description: 'Kabuto è un Pokémon fossile con una corazza dura. È molto veloce e agile.' },
    { name: 'Kabutops', description: 'Kabutops è la versione evoluta di Kabuto e ha lame affilate sulle sue zampe. È molto pericoloso in combattimento.' },
    { name: 'Aerodactyl', description: 'Aerodactyl è un Pokémon fossile che può volare rapidamente. Ha artigli affilati e una grande forza.' },
    { name: 'Snorlax', description: 'Snorlax è noto per la sua enorme dimensione e la sua tendenza a dormire. È molto difficile da svegliare.' },
    { name: 'Articuno', description: 'Articuno è un leggendario Pokémon di ghiaccio e volo. Ha il potere di controllare il ghiaccio e la neve.' },
    { name: 'Zapdos', description: 'Zapdos è un leggendario Pokémon elettrico e volante. Può generare e scaricare elettricità con grande forza.' },
    { name: 'Moltres', description: 'Moltres è un leggendario Pokémon di fuoco e volo. Le sue fiamme sono molto potenti e calde.' },
    { name: 'Dratini', description: 'Dratini è un Pokémon serpente di tipo drago. È molto agile e può evolversi in un Pokémon più potente.' },
    { name: 'Dragonair', description: 'Dragonair è una versione evoluta di Dratini e ha un aspetto elegante. Può manipolare le correnti d\'aria.' },
    { name: 'Dragonite', description: 'Dragonite è la versione evoluta di Dragonair e può volare a grande velocità. È molto potente e intelligente.' },
    { name: 'Mewtwo', description: 'Mewtwo è un Pokémon leggendario di tipo psichico creato artificialmente. È estremamente potente e ha grandi capacità psichiche.' },
    { name: 'Mew', description: 'Mew è un Pokémon leggendario con la capacità di apprendere qualsiasi mossa. È molto raro e misterioso.' }
];
